/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 netrunner_office.glb -T 
Files: netrunner_office.glb [26.98MB] > C:\Users\hp\Desktop\MERN\public\models\netrunner_office-transformed.glb [2.99MB] (89%)
Author: hell3879 (https://sketchfab.com/d43dLink)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/netrunner-office-26c794070c0346d0807c9910cf6556f0
Title: Netrunner Office
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Office(props) {
  const { nodes, materials } = useGLTF('/models/netrunner_office-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow recieveShadow geometry={nodes.defaultMaterial.geometry} material={materials.Keyboard_1011} />
      <mesh castShadow recieveShadow geometry={nodes.defaultMaterial_1.geometry} material={materials.Smartlink_1013} />
      <mesh castShadow recieveShadow geometry={nodes.defaultMaterial_2.geometry} material={materials.Smartlink_1011} />
      <mesh castShadow recieveShadow geometry={nodes.defaultMaterial_3.geometry} material={materials.Display_1003} />
      <mesh castShadow recieveShadow geometry={nodes.defaultMaterial_4.geometry} material={materials.PC_1012} />
      <mesh castShadow recieveShadow geometry={nodes.defaultMaterial_5.geometry} material={materials.PC_1011} />
      <mesh castShadow recieveShadow geometry={nodes.defaultMaterial_6.geometry} material={materials.Armchair_1002} />
      <mesh castShadow recieveShadow geometry={nodes.defaultMaterial_7.geometry} material={materials.Stol_1001} />
    </group>
  )
}

useGLTF.preload('/models/netrunner_office-transformed.glb')
